/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation("com.github.ben-manes.caffeine:caffeine:3.2.0")
}
